################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
S_UPPER_SRCS += \
../src/riscv_isa_tests/add.S \
../src/riscv_isa_tests/addw.S \
../src/riscv_isa_tests/addi.S \
../src/riscv_isa_tests/addiw.S \
../src/riscv_isa_tests/and.S \
../src/riscv_isa_tests/andi.S \
../src/riscv_isa_tests/auipc.S \
../src/riscv_isa_tests/beq.S \
../src/riscv_isa_tests/bge.S \
../src/riscv_isa_tests/bgeu.S \
../src/riscv_isa_tests/blt.S \
../src/riscv_isa_tests/bltu.S \
../src/riscv_isa_tests/bne.S \
../src/riscv_isa_tests/jal.S \
../src/riscv_isa_tests/jalr.S \
../src/riscv_isa_tests/lb.S \
../src/riscv_isa_tests/lbu.S \
../src/riscv_isa_tests/lh.S \
../src/riscv_isa_tests/lhu.S \
../src/riscv_isa_tests/lui.S \
../src/riscv_isa_tests/lw.S \
../src/riscv_isa_tests/lwu.S \
../src/riscv_isa_tests/ld.S \
../src/riscv_isa_tests/or.S \
../src/riscv_isa_tests/ori.S \
../src/riscv_isa_tests/sb.S \
../src/riscv_isa_tests/sh.S \
../src/riscv_isa_tests/sw.S \
../src/riscv_isa_tests/sd.S \
../src/riscv_isa_tests/sll.S \
../src/riscv_isa_tests/slli.S \
../src/riscv_isa_tests/slliw.S \
../src/riscv_isa_tests/sllw.S \
../src/riscv_isa_tests/slt.S \
../src/riscv_isa_tests/sltu.S \
../src/riscv_isa_tests/slti.S \
../src/riscv_isa_tests/sltiu.S \
../src/riscv_isa_tests/sra.S \
../src/riscv_isa_tests/sraw.S \
../src/riscv_isa_tests/srai.S \
../src/riscv_isa_tests/sraiw.S \
../src/riscv_isa_tests/srl.S \
../src/riscv_isa_tests/srlw.S \
../src/riscv_isa_tests/srli.S \
../src/riscv_isa_tests/srliw.S \
../src/riscv_isa_tests/sub.S \
../src/riscv_isa_tests/subw.S \
../src/riscv_isa_tests/xor.S \
../src/riscv_isa_tests/xori.S \
../src/riscv_isa_tests/div.S \
../src/riscv_isa_tests/divu.S \
../src/riscv_isa_tests/divw.S \
../src/riscv_isa_tests/divuw.S \
../src/riscv_isa_tests/mul.S \
../src/riscv_isa_tests/mulh.S \
../src/riscv_isa_tests/mulhsu.S \
../src/riscv_isa_tests/mulhu.S \
../src/riscv_isa_tests/mulw.S \
../src/riscv_isa_tests/rem.S \
../src/riscv_isa_tests/remu.S \
../src/riscv_isa_tests/remw.S \
../src/riscv_isa_tests/remuw.S \
../src/riscv_isa_tests/amoadd_d.S \
../src/riscv_isa_tests/amoadd_w.S \
../src/riscv_isa_tests/amoand_d.S \
../src/riscv_isa_tests/amoand_w.S \
../src/riscv_isa_tests/amomax_d.S \
../src/riscv_isa_tests/amomaxu_d.S \
../src/riscv_isa_tests/amomaxu_w.S \
../src/riscv_isa_tests/amomax_w.S \
../src/riscv_isa_tests/amomin_d.S \
../src/riscv_isa_tests/amominu_d.S \
../src/riscv_isa_tests/amominu_w.S \
../src/riscv_isa_tests/amomin_w.S \
../src/riscv_isa_tests/amoor_d.S \
../src/riscv_isa_tests/amoor_w.S \
../src/riscv_isa_tests/amoswap_d.S \
../src/riscv_isa_tests/amoswap_w.S \
../src/riscv_isa_tests/amoxor_d.S \
../src/riscv_isa_tests/amoxor_w.S \
../src/riscv_isa_tests/lrsc.S \
../src/riscv_isa_tests/csr.S \
../src/riscv_isa_tests/scall.S \
../src/riscv_isa_tests/sbreak.S \
../src/riscv_isa_tests/mcsr.S \
../src/riscv_isa_tests/ma_addr.S \
../src/riscv_isa_tests/ma_fetch.S \
../src/riscv_isa_tests/access.S \
../src/riscv_isa_tests/wfi.S \



OBJS += \
./src/riscv_isa_tests/add.o \
./src/riscv_isa_tests/addw.o \
./src/riscv_isa_tests/addi.o \
./src/riscv_isa_tests/addiw.o \
./src/riscv_isa_tests/and.o \
./src/riscv_isa_tests/andi.o \
./src/riscv_isa_tests/auipc.o \
./src/riscv_isa_tests/beq.o \
./src/riscv_isa_tests/bge.o \
./src/riscv_isa_tests/bgeu.o \
./src/riscv_isa_tests/blt.o \
./src/riscv_isa_tests/bltu.o \
./src/riscv_isa_tests/bne.o \
./src/riscv_isa_tests/jal.o \
./src/riscv_isa_tests/jalr.o \
./src/riscv_isa_tests/lb.o \
./src/riscv_isa_tests/lbu.o \
./src/riscv_isa_tests/lh.o \
./src/riscv_isa_tests/lhu.o \
./src/riscv_isa_tests/lui.o \
./src/riscv_isa_tests/lw.o \
./src/riscv_isa_tests/lwu.o \
./src/riscv_isa_tests/ld.o \
./src/riscv_isa_tests/or.o \
./src/riscv_isa_tests/ori.o \
./src/riscv_isa_tests/sb.o \
./src/riscv_isa_tests/sh.o \
./src/riscv_isa_tests/sw.o \
./src/riscv_isa_tests/sd.o \
./src/riscv_isa_tests/sll.o \
./src/riscv_isa_tests/slli.o \
./src/riscv_isa_tests/slliw.o \
./src/riscv_isa_tests/sllw.o \
./src/riscv_isa_tests/slt.o \
./src/riscv_isa_tests/sltu.o \
./src/riscv_isa_tests/slti.o \
./src/riscv_isa_tests/sltiu.o \
./src/riscv_isa_tests/sra.o \
./src/riscv_isa_tests/sraw.o \
./src/riscv_isa_tests/srai.o \
./src/riscv_isa_tests/sraiw.o \
./src/riscv_isa_tests/srl.o \
./src/riscv_isa_tests/srlw.o \
./src/riscv_isa_tests/srli.o \
./src/riscv_isa_tests/srliw.o \
./src/riscv_isa_tests/sub.o \
./src/riscv_isa_tests/subw.o \
./src/riscv_isa_tests/xor.o \
./src/riscv_isa_tests/xori.o \
./src/riscv_isa_tests/div.o \
./src/riscv_isa_tests/divu.o \
./src/riscv_isa_tests/divw.o \
./src/riscv_isa_tests/divuw.o \
./src/riscv_isa_tests/mul.o \
./src/riscv_isa_tests/mulh.o \
./src/riscv_isa_tests/mulhsu.o \
./src/riscv_isa_tests/mulhu.o \
./src/riscv_isa_tests/mulw.o \
./src/riscv_isa_tests/rem.o \
./src/riscv_isa_tests/remu.o \
./src/riscv_isa_tests/remw.o \
./src/riscv_isa_tests/remuw.o \
./src/riscv_isa_tests/amoadd_d.o \
./src/riscv_isa_tests/amoadd_w.o \
./src/riscv_isa_tests/amoand_d.o \
./src/riscv_isa_tests/amoand_w.o \
./src/riscv_isa_tests/amomax_d.o \
./src/riscv_isa_tests/amomaxu_d.o \
./src/riscv_isa_tests/amomaxu_w.o \
./src/riscv_isa_tests/amomax_w.o \
./src/riscv_isa_tests/amomin_d.o \
./src/riscv_isa_tests/amominu_d.o \
./src/riscv_isa_tests/amominu_w.o \
./src/riscv_isa_tests/amomin_w.o \
./src/riscv_isa_tests/amoor_d.o \
./src/riscv_isa_tests/amoor_w.o \
./src/riscv_isa_tests/amoswap_d.o \
./src/riscv_isa_tests/amoswap_w.o \
./src/riscv_isa_tests/amoxor_d.o \
./src/riscv_isa_tests/amoxor_w.o \
./src/riscv_isa_tests/lrsc.o \
./src/riscv_isa_tests/csr.o \
./src/riscv_isa_tests/scall.o \
./src/riscv_isa_tests/sbreak.o \
./src/riscv_isa_tests/mcsr.o \
./src/riscv_isa_tests/ma_addr.o \
./src/riscv_isa_tests/ma_fetch.o \
./src/riscv_isa_tests/access.o \
./src/riscv_isa_tests/wfi.o \


S_UPPER_DEPS += \
./src/riscv_isa_tests/add.d \
./src/riscv_isa_tests/addw.d \
./src/riscv_isa_tests/addi.d \
./src/riscv_isa_tests/addiw.d \
./src/riscv_isa_tests/and.d \
./src/riscv_isa_tests/andi.d \
./src/riscv_isa_tests/auipc.d \
./src/riscv_isa_tests/beq.d \
./src/riscv_isa_tests/bge.d \
./src/riscv_isa_tests/bgeu.d \
./src/riscv_isa_tests/blt.d \
./src/riscv_isa_tests/bltu.d \
./src/riscv_isa_tests/bne.d \
./src/riscv_isa_tests/jal.d \
./src/riscv_isa_tests/jalr.d \
./src/riscv_isa_tests/lb.d \
./src/riscv_isa_tests/lbu.d \
./src/riscv_isa_tests/lh.d \
./src/riscv_isa_tests/lhu.d \
./src/riscv_isa_tests/lui.d \
./src/riscv_isa_tests/lw.d \
./src/riscv_isa_tests/lwu.d \
./src/riscv_isa_tests/ld.d \
./src/riscv_isa_tests/or.d \
./src/riscv_isa_tests/ori.d \
./src/riscv_isa_tests/sb.d \
./src/riscv_isa_tests/sh.d \
./src/riscv_isa_tests/sw.d \
./src/riscv_isa_tests/sd.d \
./src/riscv_isa_tests/sll.d \
./src/riscv_isa_tests/slli.d \
./src/riscv_isa_tests/slliw.d \
./src/riscv_isa_tests/sllw.d \
./src/riscv_isa_tests/slt.d \
./src/riscv_isa_tests/sltu.d \
./src/riscv_isa_tests/slti.d \
./src/riscv_isa_tests/sltiu.d \
./src/riscv_isa_tests/sra.d \
./src/riscv_isa_tests/sraw.d \
./src/riscv_isa_tests/srai.d \
./src/riscv_isa_tests/sraiw.d \
./src/riscv_isa_tests/srl.d \
./src/riscv_isa_tests/srlw.d \
./src/riscv_isa_tests/srli.d \
./src/riscv_isa_tests/srliw.d \
./src/riscv_isa_tests/sub.d \
./src/riscv_isa_tests/subw.d \
./src/riscv_isa_tests/xor.d \
./src/riscv_isa_tests/xori.d \
./src/riscv_isa_tests/div.d \
./src/riscv_isa_tests/divu.d \
./src/riscv_isa_tests/divw.d \
./src/riscv_isa_tests/divuw.d \
./src/riscv_isa_tests/mul.d \
./src/riscv_isa_tests/mulh.d \
./src/riscv_isa_tests/mulhsu.d \
./src/riscv_isa_tests/mulhu.d \
./src/riscv_isa_tests/mulw.d \
./src/riscv_isa_tests/rem.d \
./src/riscv_isa_tests/remu.d \
./src/riscv_isa_tests/remw.d \
./src/riscv_isa_tests/remuw.d \
./src/riscv_isa_tests/amoadd_d.d \
./src/riscv_isa_tests/amoadd_w.d \
./src/riscv_isa_tests/amoand_d.d \
./src/riscv_isa_tests/amoand_w.d \
./src/riscv_isa_tests/amomax_d.d \
./src/riscv_isa_tests/amomaxu_d.d \
./src/riscv_isa_tests/amomaxu_w.d \
./src/riscv_isa_tests/amomax_w.d \
./src/riscv_isa_tests/amomin_d.d \
./src/riscv_isa_tests/amominu_d.d \
./src/riscv_isa_tests/amominu_w.d \
./src/riscv_isa_tests/amomin_w.d \
./src/riscv_isa_tests/amoor_d.d \
./src/riscv_isa_tests/amoor_w.d \
./src/riscv_isa_tests/amoswap_d.d \
./src/riscv_isa_tests/amoswap_w.d \
./src/riscv_isa_tests/amoxor_d.d \
./src/riscv_isa_tests/amoxor_w.d \
./src/riscv_isa_tests/lrsc.d \
./src/riscv_isa_tests/csr.d \
./src/riscv_isa_tests/scall.d \
./src/riscv_isa_tests/sbreak.d \
./src/riscv_isa_tests/mcsr.d \
./src/riscv_isa_tests/ma_addr.d \
./src/riscv_isa_tests/ma_fetch.d \
./src/riscv_isa_tests/access.d \
./src/riscv_isa_tests/wfi.d \


# Each subdirectory must supply rules for building sources it contributes
src/riscv_isa_tests/%.o: ../src/riscv_isa_tests/%.S
	@echo 'Building file: $<'
	@echo 'Invoking: RISC-V GCC/Newlib Assembler'
	riscv64-unknown-elf-gcc -mabi=lp64 -march=rv64ima -x assembler-with-cpp -fPIC -Wall -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -Wa,-march=rv64ima -o "$@" "$<" -I ./../src
	@echo 'Finished building: $<'
	@echo ' '


